[tool.poetry]
name = "my-llm-apps"
version = "0.1.0"
description = ""
authors = ["Junya Nakazato <nakazato_junya@ca-adv.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
